[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '5'

[[EVM.Nodes]]
Name = 'Goerli'
WSURL = 'wss://goerli.infura.io/ws/v3/85fc7c4c61664a96808975adbb581787
HTTPURL = 'https://goerli.infura.io/v3/85fc7c4c61664a96808975adbb581787'

